apiVersion: apis/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.api.namespace }}
  labels:
    api: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      api: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        api: {{ .Values.api.name }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.api.namespace }}
spec:
  selector:
    api: {{ .Values.api.name }}
  type: {{ .Values.api.service.type }}
  ports:
    - targetPort: {{ .Values.api.port }}
      port: {{ .Values.api.port }}
