apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
    namespace: {{ .Values.nginx.namespace }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        ports:
        - containerPort: {{ .Values.nginx.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  selector:
    app: {{ .Values.nginx.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.nginx.port }}
  type: {{ .Values.nginx.service.type }}
