name: Deploy with Minikube
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build api image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ../code-challenge-0.1.1/Dockerfile.rails -t maissagarrab/api:latest .
        echo -n "verifying images:"
        docker images
    - name: Build spa image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ../code-challenge-0.1.1/Dockerfile.react -t maissagarrab/spa:latest .
        echo -n "verifying images:"
        docker images
    - name: Build nginx image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ../code-challenge-0.1.1/Dockerfile.nginx -t maissagarrab/nginx:latest .
        echo -n "verifying images:"
        docker images
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Deploy to minikube
      run: helm upgrade caspar_challenge ../kubernetes --install --values=../kubernetes/values.yaml
    - name: Test service URLs
      run: "minikube service list\nminikube service example --url\necho \"------------------opening the service------------------\"\ncurl $(minikube service example --url) \n#magic___^_^___line\n#magic___^_^___line\n"
